---
# file: tasks/main.yml
# Install Oracle Java
#

- name: Download Java rpm
  get_url:
    url: "http://download.oracle.com/otn-pub/java/jdk/{{java_version_with_build}}/{{oracle_url_hash}}/jdk-{{java_version}}-linux-x64.rpm"
    dest: "/tmp/jdk-{{java_version}}-linux-x64.rpm"
    headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie;"
    mode: 0666

- name: Install Java package.
  yum:
    name: "/tmp/jdk-{{java_version}}-linux-x64.rpm"
    state: present