- hosts: "all"
  remote_user: "ec2-user"
  become: true
  become_method: sudo

  pre_tasks:
  - name: Update to latest packages
    yum:
      name: '*'
      state: latest

  roles:
    - python
    - java
    - kafka
    - health
    - cloud-init